import type { Metadata } from "next";
import { Toaster } from 'sonner';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div 
        className="w-80 h-80 bg-purple-500 absolute blur-[100px] opacity-25 top-0 left-0"
        />
        <div 
        className="w-80 h-80 bg-blue-500 absolute blur-[100px] opacity-25 bottom-0 right-0"
        />
        {children}
        <Toaster position="top-right" richColors /> 
      </body>
    </html>
  );
}
